'use client';

import Image from 'next/image';
import { useState } from 'react';

// This will be generated by the image generation script
// For now, we'll use a fallback empty object
let imageManifest: Record<string, any> = {};

try {
  imageManifest = require('./image-manifest.json').images || {};
} catch (e) {
  console.warn('Image manifest not found, using fallback rendering');
}

interface ResponsiveImageProps {
  src: string;
  alt: string;
  variant?: 'xl' | 'lg' | 'md' | 'sm' | 'xs' | 'optimized';
  fill?: boolean;
  width?: number;
  height?: number;
  sizes?: string;
  className?: string;
  loading?: 'lazy' | 'eager';
  priority?: boolean;
  quality?: number;
  onClick?: () => void;
  onLoad?: () => void;
}

/**
 * Responsive Image Component
 * Uses the generated image manifest to serve optimized responsive variants
 * Falls back to original image if manifest not available
 */
export function ResponsiveImage({
  src,
  alt,
  variant = 'xl',
  fill,
  width,
  height,
  sizes,
  className,
  loading = 'lazy',
  priority = false,
  quality,
  onClick,
  onLoad,
}: ResponsiveImageProps) {
  const [imageLoaded, setImageLoaded] = useState(false);
  const [hasError, setHasError] = useState(false);

  // Extract relative path from src
  const relativePath = src.replace('/images/events-page/', '');
  const imageData = imageManifest[relativePath];

  // Determine which image to use
  let imageSrc = src;
  let placeholder: string | undefined;

  if (imageData && imageData.variants && imageData.variants[variant]) {
    imageSrc = imageData.variants[variant].path;
    placeholder = imageData.placeholder;
  }

  // Handle image load
  const handleLoad = () => {
    setImageLoaded(true);
    onLoad?.();
  };

  // Handle error
  const handleError = () => {
    setHasError(true);
    // Fallback to original src
    console.warn(`Failed to load optimized image: ${imageSrc}, falling back to original`);
  };

  // Build srcset if we have variants
  let srcSet: string | undefined;
  if (imageData && imageData.variants) {
    const srcSetArray = Object.entries(imageData.variants)
      .filter(([key]) => ['xl', 'lg', 'sm'].includes(key))
      .map(([_, data]: [string, any]) => `${data.path} ${data.width}w`)
      .join(', ');

    if (srcSetArray) {
      srcSet = srcSetArray;
    }
  }

  return (
    <Image
      src={hasError ? src : imageSrc}
      alt={alt}
      fill={fill}
      width={width}
      height={height}
      sizes={sizes}
      srcSet={srcSet}
      className={`${className} ${!imageLoaded ? 'skeleton-loader' : ''}`}
      loading={loading}
      priority={priority}
      quality={quality}
      onClick={onClick}
      onLoad={handleLoad}
      onError={handleError}
      placeholder={placeholder && !hasError ? 'blur' : undefined}
      blurDataURL={placeholder}
    />
  );
}

/**
 * Hook to get image data from manifest
 */
export function useImageData(src: string) {
  const relativePath = src.replace('/images/events-page/', '');
  return imageManifest[relativePath] || null;
}

/**
 * Helper to get srcset for manual implementation
 */
export function getImageSrcSet(src: string): string | null {
  const relativePath = src.replace('/images/events-page/', '');
  const imageData = imageManifest[relativePath];

  if (!imageData || !imageData.variants) {
    return null;
  }

  return Object.entries(imageData.variants)
    .filter(([key]) => ['xl', 'lg', 'sm'].includes(key))
    .map(([_, data]: [string, any]) => `${data.path} ${data.width}w`)
    .join(', ');
}

/**
 * Helper to get placeholder data URL
 */
export function getImagePlaceholder(src: string): string | null {
  const relativePath = src.replace('/images/events-page/', '');
  const imageData = imageManifest[relativePath];

  return imageData?.placeholder || null;
}
